$ kubectl annotate pod mypod key1=value1 key2=value2

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  annotations:
    description: Deployment based PoC dates 2nd Mar'2022

$ kubectl run saved --image=nginx:alpine --save-config=true
$ kubectl get pod saved -o yaml